### ISSUE TITLE
Wrong name of package "xfsprogs"

### ISSUE THREAD

**Issue by mpastor** [andsens/build-debian-cloud#1]
Entered wrong name of package "xfsprogs":

diff --git a/tasks/host-dependencies b/tasks/host-dependencies
index 2a4e206..a8be1c4 100755
--- a/tasks/host-dependencies
+++ b/tasks/host-dependencies
@@ -1,6 +1,6 @@
 #!/bin/bash
 # Install packages on the builing system to make the rest of this script run smoothly.
-apt-get install -y bzip2 binutils unzip debootstrap openssl curl ca-certificates default-jre-headless xfs
+apt-get install -y bzip2 binutils unzip debootstrap openssl curl ca-certificates default-jre-headless xfsprogs

**Comment by andsens** [comment]
Hah! Now the startup message "Starting X font server: xfs." begins to make sense! :-)
