### ISSUE TITLE
wget with option `--quiet` hides need to install ssl certificates

### ISSUE THREAD

**Issue by ghost** [andsens/build-debian-cloud#111]
When certifcates are not installed for wget, running ./build-debian-cloud ec2 gives the following error.

```
Run task: 05-install-euca2ools

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/home/admin/build-debian-cloud-master/tasks/ec2/05-install-euca2ools: line 15: cd: euca2ools-1.3.2: No such file or directory
make: *** No targets specified and no makefile found.  Stop.

Bootstrapping failed!
```

Running `sudo apt-get install ca-certificates` solves the problem, but currently the use of `wget -q` in tasks/ec2/05-install-euca2ools makes it harder to find what the actual problem is.

**Comment by andsens** [comment]
Nice catch!
That'll need to be added to https://github.com/andsens/build-debian-cloud/blob/master/tasks/ec2/01-packages-ec2
I'll try to get a fix up in the weekend.
