### ISSUE TITLE
(suggestions please!) Write plugin to include standard packages

### ISSUE THREAD

**Issue by andsens** [andsens/build-debian-cloud#19]
The packages installed right now are at a bare minimum, which is fine.
Most installations share some common denominators however, a plugin which adds those packages, would be nice.
Any input as to which packages that should be would be very welcome.

EDIT: The current list can be seen [here](https://github.com/andsens/ec2debian-build-ami/blob/master/plugins/standard-packages-tasks/add-standard-packages)

**Comment by andsens** [comment]
lsb-release was removed from the main bootstrapping script, because it was not crucial.
I do think this should be one of the packages in this plugin though.

**Comment by bgupta** [comment]
cloud-init at the minimum.. everything else can be dealt with from there.

**Comment by andsens** [comment]
That's actually what #10 is for. cloud-init is still experimental in both squeeze and wheezy, so I wouldn't consider it a standard package just yet. I will make a separate plugin which pins that package though.

**Comment by bgupta** [comment]
Cool.. what about cloud-utils, which has the ec2metadata command? (And any other ec2 specific utils, like the cli tools) ec2-api-tools (Note I am largely thinking of ubuntu packages that are kinda critical for running ubuntu in the cloud, and would be very useful to running debian.)

**Comment by andsens** [comment]
http://www.debian.org/devel/wnpp/being_packaged.en.html

> Packages being worked on
> cloud-utils: cloud image management utilities, 431 days in preparation, last activity 236 days ago.

I think it's going to be a while before it makes it to debian.

**Comment by andsens** [comment]
Sudo should be added as well.

**Comment by yanfalies** [comment]
Haveged would be a nice addition. Helps with lots of operations that use entropy.

**Comment by andrewfenn** [comment]
FIrst thing off the top of my head for plugin suggestions would be possibly apparmor and/or selinux.

**Comment by andsens** [comment]
With manifests in the python branch, this is no longer necessary. People can easily specify which packages they want.
