### ISSUE TITLE
Required update initrd after grub is configured

### ISSUE THREAD

**Issue by mpastor** [andsens/build-debian-cloud#2]
Required update initrd after grub is configured otherwise instance will not boot:

diff --git a/tasks/grub b/tasks/grub
index 452ce66..9df14c4 100755
--- a/tasks/grub
+++ b/tasks/grub
@@ -10,3 +10,5 @@ root (hd0)
 kernel /boot/vmlinuz-2.6.32-5-xen-amd64 root=/dev/xvda1 ro
 initrd /boot/initrd.img-2.6.32-5-xen-amd64
 EOF
+
+update-initramfs -u -k 2.6.32-5-xen-amd64

**Comment by andsens** [comment]
Are you sure about this? I mean, it can't hurt.
We are using PvGrub though, which means only Xen should be concerned with the contents of the menu.lst.
initrd is updated when we install the kernel with apt, why would changing the menu.lst require another update?

**Comment by mpastor** [comment]
I think it can hurt :). The task "kernel" is runnning before task "grub", where is grub configured. So you must update initrd to accept changes. If i dont do that instance doesn't boot and stop at grub. then i try it with this change and it worked.

**Comment by andsens** [comment]
No I mean, it can't hurt to run it again as per your suggestion.
I tried to run it yesterday and somehow I am also having problems booting up now.
What I mean is: update-initramfs does not change its behaviour depending on the contents of menu.lst
And that is all I do in the grub task, I create a file, I don't even install grub on the system.
Could you make sure that this is the only thing that enables you to boot up the image?

**Comment by andsens** [comment]
I'm sorry, you were right: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=427509
Seems like update-initramfs _does_ look at the menu.lst
A fix is on its way :-)

**Comment by mpastor** [comment]
This fix will not work with arch i386 or when then kernel change name. Maybe better solution would by use:

$ update-initramfs -u -k all

which should update all kernel versions.

**Comment by andsens** [comment]
You're right. But the menu.lst would need updating anyways.
I think the only way to make this work in a generic way is to actually install grub and let it generate the file and run update-initramfs (if it does that).
I have open #9 for that purpose.
