### ISSUE TITLE
Mounting local filesystem boot error

### ISSUE THREAD

**Issue by andsens** [andsens/build-debian-cloud#22]
There is an error when "Mounting local filesystem", in the bootmessage

```
Mounting local filesystems...
    [31mfailed.
    [39;49m
```

**Comment by joshkraemer** [comment]
According to http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=425199, there are two solutions for this issue.

1.) Mount with noproc

Change line 30 of /etc/init.d/mountall.sh from `mount -a -t nonfs,nfs4,smbfs,cifs,ncp,ncpfs,coda,ocfs2,gfs,gfs2` to `mount -a -t nonfs,nfs4,smbfs,cifs,ncp,ncpfs,coda,ocfs2,gfs,gfs2,noproc`

2.) Remove `none       /proc proc    defaults 0 0` from fstab

I haven't tested either of these so I can't verify if they work. But when I get some time I may do it.

**Comment by andsens** [comment]
Sweet. Thanks for the effort. He says noproc is the solution, but at the same time he mentions that /proc should not even be present in the fstab. In my mind this makes 2. the better option. I will test it out today.
