### ISSUE TITLE
Hostname matches instance that created the image

### ISSUE THREAD

**Issue by JamesBromberger** [andsens/build-debian-cloud#27]
Hello,
Awesome script.
I created an AMI on a host with hostname ip-10-130-29-xxx. I then launched this AMI, and the created images had /etc/hostname set to this hostname from the instance that created the AMI. Also, the motd referenced the host that created the image. Does this need a patch to ./tasks/70-cleanup to tidy up?
  James
jeb@debian.org

**Comment by andsens** [comment]
Hi there,
thanks! :-)
Are you very sure about this? Meaning you have not some custom plugin running?
In bb0aaf3596 I removed the line which deletes `/etc/hostname`, because I found that it was not created.
When I launch an instance the motd reflects the internal IP of the machine.

I will have to check this out, most of the time I am testing the script while using my [autohostname](/secoya/ec2-autohostname) script, maybe it interferes with some diagnoses I have made.

**Comment by JamesBromberger** [comment]
Hi - no, I didn't enable any plugins, just filesystem ext4 and root partition 8 GB -- all else default. You can have a look at the AMI I made - in Singapore it is ami-82fcbcd0 (source 379101102735/debian-squeeze-amd64-20121026). I have spun about 7 instances now and they have all had /etc/hostname set tot he same (which then all appears on the command prompt by default)

I'm also wondering about UserData possibly not working.... but perhaps thats another thread or a well known issue? I know cloud-init is in experimental...

**Comment by andsens** [comment]
I'll try to find time to fix it this weekend.
About the userdata: I have inverted the functionality, ec2-run-userdata is not included by default any longer. Instead you will need to include the plugin from the `plugins/` dir.
The no-ec2-run-userdata plugin was just awkward to work with, it would have to remove the file package from the list of packages to be installed, but that could conflict with other plugins needing it etc.
Changeset: 9b81feea0b
I should probably start writing a changelog... heh.

**Comment by JamesBromberger** [comment]
On 27/10/2012 6:40 PM, Anders Ingemann wrote:

> I'll try to find time to fix it this weekend.
> 
> Ta. I'm looking to generate some images in every Region worldwide, I'd
> love to have a conversation off-list (tracker): james_AT_rcpt.to.
> 
> About the userdata: I have inverted the functionality,
> ec2-run-userdata is not included by default any longer. Instead you
> will need to include the plugin from the |plugins/| dir.
> The no-ec2-run-userdata plugin was just awkward to work with, it would
> have to remove the file package from the list of packages to be
> installed, but that could conflict with other plugins needing it etc.
> Changeset: 9b81fee
> https://github.com/andsens/ec2debian-build-ami/commit/9b81feea0b
> I should probably start writing a changelog... heh.

I think we're on a separate issue, but _--plugin
plugins/ec2-run-user-data_ gives:
/_The task plugins/ec2-run-user-data-tasks/add-ec2-run-user-data does
not exist._/

  James

## 

/Mobile:/ +61 422 166 708, /Email:/ james_AT_rcpt.to
PLUG President 2012: http://www.plug.org.au <http//www.plug.org.au>

**Comment by andsens** [comment]
Reproducible. Although `/etc/hostname` is simply set to `localhost` on my image.
The motd indeed refers to the instance the image was bootstrapped on.
Usually I just check the running instances for errors, I didn't check the snapshot itself.
`/etc/motd` is changed to the actual hostname once you boot the instance.
