### ISSUE TITLE
mkfs.xfs - force overwrite

### ISSUE THREAD

**Issue by mpastor** [andsens/build-debian-cloud#3]
When EBS contains any fs you need the -f option to force overwrite:

diff --git a/tasks/create-volume b/tasks/create-volume
index bbd7bcd..e23b9ae 100755
--- a/tasks/create-volume
+++ b/tasks/create-volume
@@ -41,7 +41,7 @@ do
        attachment_status=`ec2-describe-volumes | grep "ATTACHMENT      $volume_id" | awk '{print $5}'`
 done
 echo "Formatting the device $device_path with $filesystem"
-mkfs.$filesystem $device_path
+mkfs.$filesystem -f $device_path
 mount $device_path $builddir
 echo "The EBS volume has been formatted and mounted"

**Comment by andsens** [comment]
I don't agree on this one, the omission of -f is on purpose. An automated tool should not simply format en entire volume regardless of it's contents.
This only fails when mounting an already existing volume specified by the user - who may have specified the wrong volume.

**Comment by mpastor** [comment]
Hmmm ok, its a matter of opinion :)

**Comment by andsens** [comment]
I think I'll add a --force parameter instead -- I can see how this could be annoying when reusing a volume to test the script multiple times.

**Comment by andsens** [comment]
I have changed the behaviour of the script with 10fdf3c068, you cannot use existing volumes any longer, they have to be created by the script.
It's simply a matter of less moving parts for simplicity and stability.
