### ISSUE TITLE
Ec2 regions issue

### ISSUE THREAD

**Issue by mpastor** [andsens/build-debian-cloud#5]
Script doesn't work at all when using e.g. EBS in EU location even if parameter "--region" is used because default is always US location so API commands will fail. It would be better to work in one location:

diff --git a/ec2debian-build-ami b/ec2debian-build-ami
index 6e49d2d..07623ac 100755
--- a/ec2debian-build-ami
+++ b/ec2debian-build-ami
@@ -208,6 +208,8 @@ if [ ! -f $EC2_PRIVATE_KEY ]; then
        die "$0: AWS private key file not found: $EC2_PRIVATE_KEY"
 fi

+export EC2_URL="https://$region.ec2.amazonaws.com"
+
 if [ -z "$ebs" ]; then

**Comment by andsens** [comment]
Ah yes, just like #4. Problem was, I had all the right env vars loaded while testing so I could reduce the amount of cli arguments. I have applied all your patches except #2 and am testing right now :-)

**Comment by andsens** [comment]
This will not work if you have the EC2_URL set as an env var already.
Gotta check with -z first.

**Comment by mpastor** [comment]
When i run script on instance in EU and use "--ebs" option but not "--volume-id", script fail in task "create-volume" because it wants create an EBS in correct "availability-zone" (obtained from "meta-data"), but region isn't specified (and default is "us-east-1").

**Comment by andsens** [comment]
This should fix itself once EC2_URL gets exported I believe.
