### ISSUE TITLE
Only need $local_fs to generate hostkeys

### ISSUE THREAD

**Issue by andsens** [andsens/build-debian-cloud#57]
The generate-ssh-hostkeys script currently waits for the [network to start](https://github.com/andsens/ec2debian-build-ami/blob/master/init.d/generate-ssh-hostkeys#L4) before generating keys, in fact we only need the local filesystem to be present, no network connection is needed.

**Comment by yanfalies** [comment]
It may be a left over from using the network as a source of entropy. Haveged is a much better source as it uses CPU sampling and works well in virtualized environments.
