### ISSUE TITLE
Update to support 'jessie' 

### ISSUE THREAD

**Issue by ghost** [andsens/build-debian-cloud#70]
Great work!

I would be good to be able to specify the current debian 'testing' version generically or by code name.  :)

Cheers,
Andrew.

**Comment by andsens** [comment]
This is certainly something that is possible, it will need some testing, but mostly I think it is a matter of allowing more values in the "release" parameters.

**Comment by DrivenLogic** [comment]
The wheezy image upgrades to jessie without issue...

Point me in the right direction, and I will put together a pull request next time i spin up an image. :)

**Comment by andsens** [comment]
OK, so it seems there is actually no check going on, just a task inclusion based on the release name:
https://github.com/andsens/build-debian-cloud/blob/master/build-debian-cloud#L79

**Comment by DrivenLogic** [comment]
Ok cool, does that mean it will "just work"™  ?

**Comment by andsens** [comment]
Well, no. You will want to symlink the "wheezy" directory to match your release name, otherwise a load of tasks wont be run.

**Comment by andsens** [comment]
Fixed with #128 in the python version (use then release name "unstable").
