### ISSUE TITLE
RightScale plugin available

### ISSUE THREAD

**Issue by boltronics** [andsens/build-debian-cloud#72]
Feel free to link to (or merge in) this plugin repo.

https://github.com/sitepoint/debian-cloud-rightscale

I don't work for RightScale, but have used their services.

**Comment by andsens** [comment]
Whoa, nice job! Will definitely link to this :-)

**Comment by andsens** [comment]
Woops, forgot to close this one (fixed in https://github.com/andsens/build-debian-cloud/commit/96ee7dd024a88fb5ec671645b70ce5bddcf17684).
