### ISSUE TITLE
Verify dist-upgrade squeeze->wheezy

### ISSUE THREAD

**Issue by andsens** [andsens/build-debian-cloud#73]
Andrew Stone andrew@drivenlogic.com.au reported that the upgrade from squeeze to wheezy failed (or mor precise: the kernel remained on 2.6 after a reboot).

**Comment by andsens** [comment]
@JamesBromberger seems to have found the problem:

> I believe our Squeeze amd64 AMIs didn’t include linux-image-amd64, and so this doesn’t pull in a newer kernel when upgrading to Wheezy. I suggest: apt-get update && apt-get install –y linux-image-amd64 for AMD64 (and linux-image-486 for i386) before doing a change to Wheezy to pull in the latest kernel; I think for the next Wheezy release we should ensure we include these meta-packages for the respective architectures.

**Comment by Stonie** [comment]
Glad I could help, sorry about the top posting on the mailing list!  I forgot where I was! :)
