### ISSUE TITLE
Make images for VirtualBox.

### ISSUE THREAD

**Issue by NodeGuy** [andsens/build-debian-cloud#94]
I am designing an application for Amazon EC2 and I want to develop locally so I can iterate faster.  I can install Debian's ISO on VirtualBox but I would prefer to have an installation that matches my Amazon EC2 AMI as closely as possible.

**Comment by andsens** [comment]
[Working on it](https://github.com/andsens/build-debian-cloud/tree/python/providers) :-)

**Comment by NodeGuy** [comment]
Great!
